version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/attendance_tracker

hooks:
  BeforeInstall:
    - location: cleanup.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
