name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ec2-user/attendance-app"

      - name: SSH and Restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/attendance_app
            source venv/bin/activate
            pip install -r requirements.txt
            pkill gunicorn || true
            nohup gunicorn -w 2 -b 0.0.0.0:8080 app:app &